// <auto-generated />
using System;
using KasaDefteriApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KasaDefteriApp.Migrations
{
    [DbContext(typeof(KasaDbContext))]
    [Migration("20251130171636_FinalInitialCreate")]
    partial class FinalInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("KasaDefteriApp.Models.Islem", b =>
                {
                    b.Property<int>("IslemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IslemAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IslemDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IslemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IslemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KasaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("IslemID");

                    b.HasIndex("KasaID");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("KasaDefteriApp.Models.Kasa", b =>
                {
                    b.Property<int>("KasaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("KasaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KasaID");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("KasaDefteriApp.Models.Islem", b =>
                {
                    b.HasOne("KasaDefteriApp.Models.Kasa", "Kasa")
                        .WithMany("Islems")
                        .HasForeignKey("KasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasa");
                });

            modelBuilder.Entity("KasaDefteriApp.Models.Kasa", b =>
                {
                    b.Navigation("Islems");
                });
#pragma warning restore 612, 618
        }
    }
}
